# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIFiles/EditWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditWindow(object):
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(500, 224)
        self.gridLayout_2 = QtWidgets.QGridLayout(EditWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.editDialog = QtWidgets.QDialogButtonBox(EditWindow)
        self.editDialog.setOrientation(QtCore.Qt.Horizontal)
        self.editDialog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.editDialog.setObjectName("editDialog")
        self.gridLayout.addWidget(self.editDialog, 4, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.noiseFrame = QtWidgets.QFrame(EditWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noiseFrame.sizePolicy().hasHeightForWidth())
        self.noiseFrame.setSizePolicy(sizePolicy)
        self.noiseFrame.setStyleSheet("")
        self.noiseFrame.setObjectName("noiseFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.noiseFrame)
        self.horizontalLayout_5.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bellRadioButton = QtWidgets.QRadioButton(self.noiseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bellRadioButton.sizePolicy().hasHeightForWidth())
        self.bellRadioButton.setSizePolicy(sizePolicy)
        self.bellRadioButton.setObjectName("bellRadioButton")
        self.horizontalLayout_5.addWidget(self.bellRadioButton)
        self.userRadioButton = QtWidgets.QRadioButton(self.noiseFrame)
        self.userRadioButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userRadioButton.sizePolicy().hasHeightForWidth())
        self.userRadioButton.setSizePolicy(sizePolicy)
        self.userRadioButton.setObjectName("userRadioButton")
        self.horizontalLayout_5.addWidget(self.userRadioButton)
        self.noneRadioButton = QtWidgets.QRadioButton(self.noiseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noneRadioButton.sizePolicy().hasHeightForWidth())
        self.noneRadioButton.setSizePolicy(sizePolicy)
        self.noneRadioButton.setObjectName("noneRadioButton")
        self.horizontalLayout_5.addWidget(self.noneRadioButton)
        self.horizontalLayout_4.addWidget(self.noiseFrame)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.intervalLineEdit = QtWidgets.QLineEdit(EditWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalLineEdit.sizePolicy().hasHeightForWidth())
        self.intervalLineEdit.setSizePolicy(sizePolicy)
        self.intervalLineEdit.setObjectName("intervalLineEdit")
        self.horizontalLayout_3.addWidget(self.intervalLineEdit)
        self.intervalComboBox = QtWidgets.QComboBox(EditWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalComboBox.sizePolicy().hasHeightForWidth())
        self.intervalComboBox.setSizePolicy(sizePolicy)
        self.intervalComboBox.setObjectName("intervalComboBox")
        self.intervalComboBox.addItem("")
        self.intervalComboBox.addItem("")
        self.intervalComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.intervalComboBox)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.webpageLabel = QtWidgets.QLabel(EditWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webpageLabel.sizePolicy().hasHeightForWidth())
        self.webpageLabel.setSizePolicy(sizePolicy)
        self.webpageLabel.setObjectName("webpageLabel")
        self.gridLayout.addWidget(self.webpageLabel, 1, 0, 1, 1)
        self.alertLabel = QtWidgets.QLabel(EditWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alertLabel.sizePolicy().hasHeightForWidth())
        self.alertLabel.setSizePolicy(sizePolicy)
        self.alertLabel.setObjectName("alertLabel")
        self.gridLayout.addWidget(self.alertLabel, 3, 0, 1, 1)
        self.titleLabel = QtWidgets.QLabel(EditWindow)
        self.titleLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLineEdit = QtWidgets.QLineEdit(EditWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLineEdit.sizePolicy().hasHeightForWidth())
        self.titleLineEdit.setSizePolicy(sizePolicy)
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.horizontalLayout.addWidget(self.titleLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.webpageLineEdit = QtWidgets.QLineEdit(EditWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webpageLineEdit.sizePolicy().hasHeightForWidth())
        self.webpageLineEdit.setSizePolicy(sizePolicy)
        self.webpageLineEdit.setObjectName("webpageLineEdit")
        self.horizontalLayout_2.addWidget(self.webpageLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.intervalLabel = QtWidgets.QLabel(EditWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalLabel.sizePolicy().hasHeightForWidth())
        self.intervalLabel.setSizePolicy(sizePolicy)
        self.intervalLabel.setObjectName("intervalLabel")
        self.gridLayout.addWidget(self.intervalLabel, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.webpageLabel.setBuddy(self.webpageLineEdit)
        self.titleLabel.setBuddy(self.titleLineEdit)
        self.intervalLabel.setBuddy(self.intervalLineEdit)

        self.retranslateUi(EditWindow)
        self.editDialog.accepted.connect(EditWindow.accept)
        self.editDialog.rejected.connect(EditWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(EditWindow)

    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "Edit"))
        self.bellRadioButton.setText(_translate("EditWindow", "Be&ll"))
        self.userRadioButton.setText(_translate("EditWindow", "&User"))
        self.noneRadioButton.setText(_translate("EditWindow", "&None"))
        self.intervalComboBox.setItemText(0, _translate("EditWindow", "Second(s)"))
        self.intervalComboBox.setItemText(1, _translate("EditWindow", "Minute(s)"))
        self.intervalComboBox.setItemText(2, _translate("EditWindow", "Hour(s)"))
        self.webpageLabel.setText(_translate("EditWindow", "Webpa&ge"))
        self.alertLabel.setText(_translate("EditWindow", "Noise"))
        self.titleLabel.setText(_translate("EditWindow", "Title"))
        self.intervalLabel.setText(_translate("EditWindow", "&Interval"))

