# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UIFiles/OptionsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptionsWindow(object):
    def setupUi(self, OptionsWindow):
        OptionsWindow.setObjectName("OptionsWindow")
        OptionsWindow.resize(500, 173)
        self.gridLayout = QtWidgets.QGridLayout(OptionsWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(OptionsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.soundLineEdit = QtWidgets.QLineEdit(self.frame)
        self.soundLineEdit.setEnabled(False)
        self.soundLineEdit.setReadOnly(True)
        self.soundLineEdit.setObjectName("soundLineEdit")
        self.gridLayout_2.addWidget(self.soundLineEdit, 3, 1, 1, 1)
        self.soundDirButton = QtWidgets.QPushButton(self.frame)
        self.soundDirButton.setEnabled(False)
        self.soundDirButton.setObjectName("soundDirButton")
        self.gridLayout_2.addWidget(self.soundDirButton, 3, 2, 1, 1)
        self.logDirButton = QtWidgets.QPushButton(self.frame)
        self.logDirButton.setEnabled(False)
        self.logDirButton.setObjectName("logDirButton")
        self.gridLayout_2.addWidget(self.logDirButton, 1, 2, 1, 1)
        self.customBox = QtWidgets.QCheckBox(self.frame)
        self.customBox.setObjectName("customBox")
        self.gridLayout_2.addWidget(self.customBox, 3, 0, 1, 1)
        self.logLineEdit = QtWidgets.QLineEdit(self.frame)
        self.logLineEdit.setEnabled(False)
        self.logLineEdit.setReadOnly(True)
        self.logLineEdit.setObjectName("logLineEdit")
        self.gridLayout_2.addWidget(self.logLineEdit, 1, 1, 1, 1)
        self.logBox = QtWidgets.QCheckBox(self.frame)
        self.logBox.setEnabled(True)
        self.logBox.setChecked(False)
        self.logBox.setObjectName("logBox")
        self.gridLayout_2.addWidget(self.logBox, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.optionsDialog = QtWidgets.QDialogButtonBox(OptionsWindow)
        self.optionsDialog.setOrientation(QtCore.Qt.Horizontal)
        self.optionsDialog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.optionsDialog.setObjectName("optionsDialog")
        self.gridLayout.addWidget(self.optionsDialog, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.soundBox = QtWidgets.QCheckBox(OptionsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soundBox.sizePolicy().hasHeightForWidth())
        self.soundBox.setSizePolicy(sizePolicy)
        self.soundBox.setObjectName("soundBox")
        self.horizontalLayout_4.addWidget(self.soundBox)
        self.notificationBox = QtWidgets.QCheckBox(OptionsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notificationBox.sizePolicy().hasHeightForWidth())
        self.notificationBox.setSizePolicy(sizePolicy)
        self.notificationBox.setObjectName("notificationBox")
        self.horizontalLayout_4.addWidget(self.notificationBox)
        self.startupBox = QtWidgets.QCheckBox(OptionsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startupBox.sizePolicy().hasHeightForWidth())
        self.startupBox.setSizePolicy(sizePolicy)
        self.startupBox.setObjectName("startupBox")
        self.horizontalLayout_4.addWidget(self.startupBox)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(OptionsWindow)
        self.optionsDialog.accepted.connect(OptionsWindow.accept)
        self.optionsDialog.rejected.connect(OptionsWindow.reject)
        self.logBox.toggled['bool'].connect(self.logLineEdit.setEnabled)
        self.customBox.toggled['bool'].connect(self.soundDirButton.setEnabled)
        self.logBox.toggled['bool'].connect(self.logDirButton.setEnabled)
        self.customBox.toggled['bool'].connect(self.soundLineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(OptionsWindow)

    def retranslateUi(self, OptionsWindow):
        _translate = QtCore.QCoreApplication.translate
        OptionsWindow.setWindowTitle(_translate("OptionsWindow", "Options"))
        self.soundDirButton.setText(_translate("OptionsWindow", "Choose..."))
        self.logDirButton.setText(_translate("OptionsWindow", "Choose..."))
        self.customBox.setText(_translate("OptionsWindow", "Custom sound:"))
        self.logBox.setText(_translate("OptionsWindow", "Create log file at:"))
        self.soundBox.setText(_translate("OptionsWindow", "Enable sound"))
        self.notificationBox.setText(_translate("OptionsWindow", "Enable notifications"))
        self.startupBox.setText(_translate("OptionsWindow", "Run on startup"))

